app:
    resource: '@AppBundle/Controller/'
    type: annotation

user:
    resource: '@AppBundle/Resources/config/routing.yml'

api:
    resource: "@AppBundle/Resources/config/api_routing.yml"
    prefix:   /api